upstream fclens {
	server frontend:80;
}

upstream matomo {
	server matomo-web:80;
}

server {

    # catch all request
    listen       80 default_server;
    listen  [::]:80;
    server_name  _;

    # set DNS resolver as Docker internal DNS
    #resolver 127.0.0.11 valid=10s;
    #resolver_timeout 5s;

    # all /api request are proxified to my api inside the
    # docker compose network
    location / {
        proxy_pass http://fclens/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


}

server {
    # catch all request
    listen       90 default_server;
    listen  [::]:90;
    server_name  _;

    location / {
        proxy_pass http://matomo/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}